export const appCopy = {
  brand: 'Herceg Novi Guide',
  homeTitle: 'Istraži Herceg Novi',
  homeSubtitle:
    'Mirnije jutro, kasni ručak uz more ili večernji izlazak. Sve je složeno da brzo stignete od ideje do mape.',
  featured: 'Preporučeno za vas',
  today: 'Najbolje danas',
  nearby: 'U blizini',
  popular: 'Popularna mjesta',
  beaches: 'Za more i kupanje',
  food: 'Za hranu i piće',
  nightlife: 'Za kasnije sate',
  savedTitle: 'Sačuvano',
  savedEmptyTitle: 'Još nema sačuvanih mjesta',
  savedEmptyBody: 'Dodirnite srce na kartici ili detalju mjesta da sačuvate plan za kasnije.',
  searchPlaceholder: 'Pretraži mjesta, četvrti ili kategorije',
  searchEmptyTitle: 'Nema rezultata',
  searchEmptyBody: 'Pokušajte sa drugim nazivom, kategorijom ili uklonite neki filter.',
  retry: 'Pokušajte ponovo',
  directions: 'Uputstva',
  save: 'Sačuvaj',
  saved: 'Sačuvano',
  share: 'Podijeli',
  website: 'Sajt',
  call: 'Pozovi',
  filters: 'Filteri',
  sort: 'Sortiranje',
  openNow: 'Otvoreno sad',
  topRated: 'Najbolje ocijenjeno',
  nearest: 'Blizu mene',
  family: 'Porodice',
  culture: 'Kultura',
  foodFilter: 'Hrana',
  nightlifeFilter: 'Noćni život',
  beachesFilter: 'Plaže',
  recommendedSort: 'Preporučeno',
  nearestSort: 'Najbliže',
  ratingSort: 'Najbolje ocijenjeno',
  alphabetSort: 'A–Š',
  dataSources: 'O podacima i izvorima',
  privacy: 'Privatnost',
  aboutCity: 'Praktične informacije',
  settings: 'Podešavanja',
  languageNote: 'Jezik aplikacije',
  languageValue: 'Crnogorski (latinica)',
  locationPromptTitle: 'Prikaži mjesta u blizini',
  locationPromptBody:
    'Lokaciju koristimo samo dok tražite mjesta oko sebe ili sortirate po udaljenosti.',
  onboarding: [
    {
      title: 'Mjesta koja vrijedi otvoriti odmah',
      body: 'Najvažnije stvari su na jednoj liniji: atrakcije, hrana, plaže i večernja mjesta.',
    },
    {
      title: 'Brz put do mape',
      body: 'Dugme Uputstva otvara navigaciju odmah, bez dodatnih koraka i bez nepotrebnih dozvola.',
    },
    {
      title: 'Sačuvajte plan za kasnije',
      body: 'Označite mjesta koja želite obići i vratite im se kad budete spremni za šetnju ili izlet.',
    },
  ],
};
